name: Execute Server-Side Script on Remote Server

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Execute Script on Server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}  
        username: ${{ secrets.USER }}          
        key: ${{ secrets.SSH_PRIVATE_KEY }}  
        port: ${{ secrets.PORT }} 
        script: |
          cd /var/www/html/script; bash deploy.sh
